name       : haskell-ansi-wl-pprint
version    : 0.6.7.3
release    : 1
source     :
    - http://hackage.haskell.org/package/ansi-wl-pprint-0.6.7.3/ansi-wl-pprint-0.6.7.3.tar.gz : 3789ecaa89721eabef58ddc5711f7fd1ff67e262da1659f3b20d38a9e1f5b708
license    : BSD-3-Clause
component  : programming.haskell
summary    : This is a pretty printing library based on Wadler's paper A Prettier Printer. It has been enhanced with support for ANSI terminal colored output using the ansi-terminal package. 
description: |
    This is a pretty printing library based on Wadler's paper A Prettier Printer. It has been enhanced with support for ANSI terminal colored output using the ansi-terminal package. 
builddeps  :
    - haskell-ansi-terminal
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
