name       : haskell-ansi-wl-pprint
version    : 0.6.8.2
release    : 2
source     :
    - https://hackage.haskell.org/package/ansi-wl-pprint-0.6.8.2/ansi-wl-pprint-0.6.8.2.tar.gz : a630721bd57678c3bfeb6c703f8249e434cbf85f40daceec4660fb8c6725cb3e
license    : BSD-3-Clause
component  : programming.haskell
summary    : This is a pretty printing library based on Wadler's paper A Prettier Printer. It has been enhanced with support for ANSI terminal colored output using the ansi-terminal package.
description: "This is a pretty printing library based on Wadler's paper A Prettier Printer. It has been enhanced with support for ANSI terminal colored output using the ansi-terminal package. \n"
builddeps  :
    - haskell-ansi-terminal
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
